version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:8080"
  

  midtermapi:
    image: ${DOCKER_REGISTRY-}midtermapi
    build:
      context: .
      dockerfile: MidtermApi/Dockerfile
    ports:
      - "8081:8081"
   

networks:
  mynetwork:
    driver: bridge
